CREATE TABLE ODGAJIVAC(
	id_odgajivac INT PRIMARY KEY,
	ime NVARCHAR(30) NOT NULL,
	broj_telefona NVARCHAR(30) NOT NULL,
	e_mail NVARCHAR(30) NOT NULL,
	adresa NVARCHAR(30) NOT NULL,
	drzava NVARCHAR(20) NOT NULL
)
ALTER TABLE RASA
ADD napomena NVARCHAR(30);

ALTER TABLE PAS
ADD id_odgajivac INT REFERENCES ODGAJIVAC(odgajivac_id);